# Generated by Django 4.2.7 on 2023-11-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_alter_product_brand_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
