# Generated by Django 4.2.7 on 2024-01-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0008_ownedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
