# Generated by Django 4.2.7 on 2024-01-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0009_remove_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fetched_product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
